# name of your github action
name: Deploy Release
# this will help you specify where to run
on:
  push:
    tags:
      - "v*" # this will run the action when you push a tag that starts with v
  workflow_dispatch:
# this is where the magic happens, each job happens in parallel btw
jobs:
  macos:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.5.0
        with:
          node-version: 18
      - name: Install Modules and Publish build
        run: |
          npm install
          rm -rf node_modules/sharp
          npm install --platform=darwin --arch=x64 sharp
          npm rebuild --platform=darwin --arch=arm64 sharp
          npm run publish-mac-universal-app
      - name: Upload Electron build artifact
        uses: actions/upload-artifact@v4
        with:
          name: upscayl-mac-build
          path: release/
